bdring/Grbl_Esp32

Grbl_Esp32/Grbl_Esp32.ino
Grbl_Esp32/config.h
Grbl_Esp32/coolant_control.cpp
Grbl_Esp32/cpu_map.h
Grbl_Esp32/gcode.cpp
Grbl_Esp32/gcode.h
Grbl_Esp32/grbl.h
Grbl_Esp32/grbl_bluetooth.cpp
Grbl_Esp32/grbl_sd.cpp
Grbl_Esp32/grbl_sd.h
Grbl_Esp32/motion_control.cpp
Grbl_Esp32/protocol.cpp
Grbl_Esp32/report.cpp
Grbl_Esp32/report.h
Grbl_Esp32/serial.cpp
Grbl_Esp32/serial.h
Grbl_Esp32/settings.cpp
Grbl_Esp32/spindle_control.cpp
Grbl_Esp32/spindle_control.h
Grbl_Esp32/stepper.cpp
Grbl_Esp32/system.cpp
Grbl_Esp32/system.h
README.md

Merge dev to master

---

Grbl_Esp32/web_server.cpp

Fix SD download window generate disconnection if not file

Fix Captive Portal not working

---

Grbl_Esp32/commands.cpp
Grbl_Esp32/grbl_sd.cpp
Grbl_Esp32/serial.cpp
Grbl_Esp32/serial.h
Grbl_Esp32/serial2socket.cpp
Grbl_Esp32/stepper.cpp
Grbl_Esp32/telnet_server.cpp
Grbl_Esp32/web_server.cpp
libraries/ESP32SSDP/ESP32SSDP.cpp

Note core still has some unfixed warning

Fix GRBL compilation when  compiler warning=All

---

Grbl_Esp32/wificonfig.cpp

Update Station  connection failed message

---

Grbl_Esp32/cpu_map.h
Grbl_Esp32/stepper.cpp

- Cleaned up lowrider cpu_map
- added auto squaring of z-axis to stepper .cpp

Updates for Low Rider Machine

---

Grbl_Esp32/grbl.h
Grbl_Esp32/servo_axis.cpp
Grbl_Esp32/servo_axis.h
Grbl_Esp32/servo_pen.cpp
Grbl_Esp32/solenoid_pen.cpp
platformio.ini

Hello Bart-san.
While I was studying FreeRTOS, I found code that seemed to be better corrected.
In particular, calls to vTaskDelayUntil appear to pass uninitialized variables at the first delay call.
Please merge the changes if you decide that this change is reasonable.
Regards.

Improve affinity with FreeRTOS

---

Grbl_Esp32/grbl.h
Grbl_Esp32/grbl_trinamic.cpp
Grbl_Esp32/grbl_trinamic.h
Grbl_Esp32/stepper.h

- Startup message will look something like this. [MSG:Using TMCStepper Library Ver 0x000500] to help with user support

Added TMCStepper Lib Version to startup message

---

Grbl_Esp32/config.h
Grbl_Esp32/cpu_map.h
Grbl_Esp32/gcode.cpp
Grbl_Esp32/grbl.h
Grbl_Esp32/spindle_control.cpp
Grbl_Esp32/spindle_control.h
Grbl_Esp32/stepper.cpp
doc/script/fit_nonlinear_spindle.py
doc/script/simple_stream.py
doc/script/stream.py

- Added ability to invert PWM signal [issue #224](https://github.com/bdring/Grbl_Esp32/issues/244)
- Added piecewise linear fit to correct RPM on non linear spindles [isse #247](https://github.com/bdring/Grbl_Esp32/issues/247)
- Cleaned up use of includes so not using a spindle has a cleaner cpu map.

Update Spindle Features

---

Grbl_Esp32/grbl.h
Grbl_Esp32/motion_control.cpp
Grbl_Esp32/polar_coaster.cpp

Hello Bart-san.
I have implementd G02 and G03 for the Polar Coaster.
Please merge if it fits your policy.
Thank you.

Arc support for the Polar Coaster

---

Grbl_Esp32/Grbl_Esp32.ino
Grbl_Esp32/config.h
Grbl_Esp32/grbl.h
Grbl_Esp32/web_server.cpp

Be sure everything is OFF at start

Fix WiFi upd error when in BT

---

Grbl_Esp32/grbl.h
Grbl_Esp32/spindle_control.cpp

First try at speeding up PWM by optimizing the driver code for the LED PWM hardware.

Simple speedup for spindle PWM

---

Grbl_Esp32/commands.cpp
Grbl_Esp32/config.h
Grbl_Esp32/grbl.h
Grbl_Esp32/web_server.cpp
Grbl_Esp32/wificonfig.h

by using [ESP] or [ESP0] or even [ESP-help]

Add inline help for [ESPXXX] command

---

Grbl_Esp32/Custom/atari_1020.cpp
Grbl_Esp32/Machines/atari_1020.h
Grbl_Esp32/Machines/foo_6axis.h
Grbl_Esp32/Machines/midtbot.h
Grbl_Esp32/Machines/pen_laser.h
Grbl_Esp32/Machines/polar_coaster.h
Grbl_Esp32/Machines/servo_axis.h
Grbl_Esp32/Machines/template.h
Grbl_Esp32/Machines/tmc2130_pen.h
Grbl_Esp32/machine_common.h
Grbl_Esp32/servo_axis.cpp
Grbl_Esp32/servo_axis.h
Grbl_Esp32/solenoid_pen.cpp
Grbl_Esp32/spindle_control.cpp
Grbl_Esp32/system.cpp
Grbl_Esp32/system.h

All PWM channels are auto assigned now. No need to assign them in machine definition files.

Auto assigned PWM channels

---

Grbl_Esp32/gcode.cpp
Grbl_Esp32/gcode.h
Grbl_Esp32/motion_control.cpp
Grbl_Esp32/motion_control.h
Grbl_Esp32/report.cpp
Grbl_Esp32/spindle_control.cpp

- The M56 parking feature override is now implemented
- Fixed a typo in how the spindle got a PWM channel

Parking Feature and Spindle Fix

---

Grbl_Esp32/grbl.h
Grbl_Esp32/machine.h
build-all.ps1
build-all.py
build-all.sh
build-machine.py
builder.py

The new Spindle Class is a much better solution to
the problem that add-on's were intended to address.

Removed add-on configurations

---

Grbl_Esp32/Machines/3axis_v4.h
Grbl_Esp32/Machines/4axis_external_driver.h
Grbl_Esp32/Spindles/BESCSpindle.cpp
Grbl_Esp32/Spindles/DacSpindle.cpp
Grbl_Esp32/Spindles/HuanyangSpindle.cpp
Grbl_Esp32/Spindles/Laser.cpp
Grbl_Esp32/Spindles/NullSpindle.cpp
Grbl_Esp32/Spindles/PWMSpindle.cpp
Grbl_Esp32/Spindles/RelaySpindle.cpp
Grbl_Esp32/Spindles/SpindleClass.cpp
Grbl_Esp32/Spindles/SpindleClass.h
Grbl_Esp32/gcode.cpp
Grbl_Esp32/protocol.cpp
Grbl_Esp32/report.cpp
Grbl_Esp32/report.h
Grbl_Esp32/stepper.cpp

If you take this PR, then you will be able to make a PR from Devt on top of it.

Restored Spindle files

---

Grbl_Esp32/GCodePreprocessor.cpp
Grbl_Esp32/WebSettings.cpp

Fixed problems with compiling with SD card disabled.

SD compile

---

Grbl_Esp32/grbl_trinamic.cpp

Hello, @bdring, @MitchBradley.
This is stepper's code using I2S.
I think that it is not fully incorporated into stepper.cpp and still needs to be tested and modified.
I'm happy to share the code with you in order to review and organize the new STEPPER code.
Thank you.

I2S I/O expander

---

Grbl_Esp32/Grbl_Esp32.ino
Grbl_Esp32/Machines/i2s_out_xyzabc_tmc.h
Grbl_Esp32/grbl_trinamic.cpp
Grbl_Esp32/i2s_out.cpp
Grbl_Esp32/i2s_out.h

Cleaning up some codes.
SeeAlso:
https://github.com/bdring/Grbl_Esp32/pull/427

Fixed the problem of combining I2S and TMC2130 SPI (2)

---

Grbl_Esp32/Machines/lowrider_v1p2.h

Update lowrider_v1p2.h to define probe pin

---

Grbl_Esp32/Machines/6_pack_stepstick_v1.h
Grbl_Esp32/Spindles/HuanyangSpindle.cpp
Grbl_Esp32/Spindles/SpindleClass.h
Grbl_Esp32/grbl.h
Grbl_Esp32/protocol.cpp
Grbl_Esp32/serial.cpp
Grbl_Esp32/serial.h

* Major improvements in Huanyang spindle support
* Minor change to reset fix to eliminate redundant code

Sync in preparation for big formatting change

---

Grbl_Esp32/src/i2s_out.cpp
Grbl_Esp32/src/i2s_out.h
Grbl_Esp32/src/stepper.cpp

This is a rebase of odaki's fix onto the new src/ file organization.

Fix the I2S stream generates a 3x faster pulse.

---

Grbl_Esp32/src/Defaults.h
Grbl_Esp32/src/Grbl.h
Grbl_Esp32/src/Limits.cpp
Grbl_Esp32/src/Machines/6_pack_MPCNC_stepstick_v1.h
Grbl_Esp32/src/Motors/Motor.cpp
Grbl_Esp32/src/Motors/Motors.cpp

- Added X2_LIMIT_PIN thru C2_LIMIT_PIN
- The 2 switches are simply or'd in the logic
- Limit pin difintion now prints in boot MSG's
- Cleaned up MS3 logic to use an array and defaults like limit switches
- Added a new machine definition file to test new features

Added second limit switch I/O option

---

Grbl_Esp32/Grbl_Esp32.ino
Grbl_Esp32/src/Grbl.cpp
Grbl_Esp32/src/Grbl.h
Grbl_Esp32/src/Spindles/Spindle.cpp
Grbl_Esp32/src/System.cpp

... while moving some variable definitions
where they belong.

Cleaned up the .ino file in favor of Grbl.h

---

Grbl_Esp32/src/Config.h
Grbl_Esp32/src/Defaults.h
Grbl_Esp32/src/Grbl.h
Grbl_Esp32/src/Machines/lowrider_v1p2.h
Grbl_Esp32/src/Machines/spi_daisy_4axis_xyza.h
Grbl_Esp32/src/SettingsDefinitions.cpp
Grbl_Esp32/src/SettingsDefinitions.h
Grbl_Esp32/src/Spindles/10vSpindle.cpp
Grbl_Esp32/src/Spindles/PWMSpindle.cpp

Enable pin was turning off, but not back on in laser mode
Add new spindle settings

Laser mode fix

---

Grbl_Esp32/Custom/atari_1020.cpp

by using a ternary operator assignment

Fixed else formatting

---

Grbl_Esp32/src/WebUI/WebServer.cpp

Fix ENABLE_AUTHENTICATION

---

Grbl_Esp32/src/Grbl.h
Grbl_Esp32/src/Stepper.cpp
Grbl_Esp32/src/Stepper.h

Tested with I2S in stream and static modes

Fix step leakage with inverted steps

---

Grbl_Esp32/src/Planner.cpp
Grbl_Esp32/src/Stepper.cpp
Grbl_Esp32/src/WebUI/WebServer.cpp

Tightened up sloppy returns

---

Grbl_Esp32/Custom/polar_coaster.cpp
Grbl_Esp32/src/CoolantControl.cpp
Grbl_Esp32/src/GCode.cpp
Grbl_Esp32/src/Grbl.h
Grbl_Esp32/src/Jog.cpp
Grbl_Esp32/src/Jog.h
Grbl_Esp32/src/Limits.cpp
Grbl_Esp32/src/MotionControl.h
Grbl_Esp32/src/Motors/Dynamixel2.cpp
Grbl_Esp32/src/Motors/Motors.cpp
Grbl_Esp32/src/Motors/TrinamicDriver.cpp
Grbl_Esp32/src/Motors/UnipolarMotor.cpp
Grbl_Esp32/src/ProcessSettings.cpp
Grbl_Esp32/src/Protocol.cpp
Grbl_Esp32/src/Report.cpp
Grbl_Esp32/src/SDCard.h
Grbl_Esp32/src/Serial.cpp
Grbl_Esp32/src/Serial.h
Grbl_Esp32/src/Settings.h
Grbl_Esp32/src/Spindles/HuanyangSpindle.cpp
Grbl_Esp32/src/Spindles/Spindle.cpp
Grbl_Esp32/src/Stepper.cpp
Grbl_Esp32/src/System.h
Grbl_Esp32/src/WebUI/BTConfig.cpp
Grbl_Esp32/src/WebUI/BTConfig.h
Grbl_Esp32/src/WebUI/NotificationsService.cpp
Grbl_Esp32/src/WebUI/WebServer.cpp
Grbl_Esp32/src/WebUI/WebSettings.cpp
Grbl_Esp32/src/WebUI/WifiConfig.cpp
Grbl_Esp32/src/WebUI/WifiServices.cpp

To pick up new setting for case clauses

Ran clang-format -i on all .cpp and .h files

---

Grbl_Esp32/src/Eeprom.cpp
Grbl_Esp32/src/GCode.cpp
Grbl_Esp32/src/Motors/Dynamixel2.cpp
Grbl_Esp32/src/Report.cpp

Fixed various small bugs:
1. N_AXIS -> number_axis->get() in dynamixel2
2. EEPROM checksum error. This should have been a rotate, instead of a logical OR.
3. gc_init() checks for a wrong checksum first in ALL coordinate systems.
4. Report can give buffer overflows for 6 axis or weird floating point coordinate systems.

Fixed various small bugs

---

Grbl_Esp32/src/Eeprom.cpp
Grbl_Esp32/src/GCode.cpp
Grbl_Esp32/src/Motors/Dynamixel2.cpp
Grbl_Esp32/src/Report.cpp

* Fixed various small bugs
* Fixed potential cast bug
* Fixed double reporting of errors
Co-authored-by: Stefan de Bruijn <stefan@nubilosoft.com>

Fixed various small bugs (#605)

---

Grbl_Esp32/src/Limits.cpp

Fix the problem where dual switches were not working in inverted mode.
Wait for Chris E's testing before merging.

fixed dual switches when inverted

---

Grbl_Esp32/src/Protocol.h
Grbl_Esp32/src/Serial.cpp
Grbl_Esp32/src/Serial.h
Grbl_Esp32/src/WebUI/InputBuffer.h
Grbl_Esp32/src/WebUI/Serial2Socket.h

Basically I changed the buffers to 256 bytes.
This is a patch necessary for F360 personal license users, because they decided to add a very lengthy comment.
NOTE: I'm in doubt about the `Serial.setRxBufferSize(256);` because I'm not sure how it would respond with multiple clients attached. Please advice.

Changed buffer sizes to 256 throughout various parts of the program.

---

Grbl_Esp32/src/Grbl.h
Grbl_Esp32/src/Machines/tmc2130_pen.h

based on Slack conversation https://buildlog.slack.com/archives/CBZKZ8LHL/p1604243530253000

TMC2130 plotter machine servo config update

---

Grbl_Esp32/src/Config.h
Grbl_Esp32/src/Grbl.h
Grbl_Esp32/src/Report.cpp
Grbl_Esp32/src/Report.h
Grbl_Esp32/src/SettingsDefinitions.cpp
Grbl_Esp32/src/SettingsDefinitions.h
Grbl_Esp32/src/Spindles/PWMSpindle.cpp

- $Message/Level Setting
- ISR safe ledcWrite

Updates from PWM_ISR_Fix branch

---

Grbl_Esp32/src/WebUI/WebServer.cpp

Clean `UploadStatusType::NONE` [Discussion](https://discord.com/channels/780079161460916227/786364602223951882/817817803599904778)

Clean up -WIP

---

Grbl_Esp32/Custom/CoreXY.cpp
Grbl_Esp32/Custom/custom_code_template.cpp
Grbl_Esp32/Custom/parallel_delta.cpp
Grbl_Esp32/Custom/polar_coaster.cpp
Grbl_Esp32/src/GCode.cpp
Grbl_Esp32/src/Grbl.cpp
Grbl_Esp32/src/Grbl.h
Grbl_Esp32/src/Jog.cpp
Grbl_Esp32/src/Jog.h
Grbl_Esp32/src/Limits.cpp
Grbl_Esp32/src/Machines/midtbot.h
Grbl_Esp32/src/Machines/polar_coaster.h
Grbl_Esp32/src/Machines/tapster_3.h
Grbl_Esp32/src/Machines/tapster_pro_6P_trinamic.h
Grbl_Esp32/src/MotionControl.cpp
Grbl_Esp32/src/MotionControl.h
Grbl_Esp32/src/Planner.h
Grbl_Esp32/src/Protocol.cpp
Grbl_Esp32/src/System.cpp
Grbl_Esp32/src/System.h

Applied #741 on top of the latest Devt

New jog fix

---

Grbl_Esp32/src/Defaults.h
Grbl_Esp32/src/Grbl.h
Grbl_Esp32/src/Serial.cpp

- Also changed defaults of trinamic motor currents

Increase serial task stack size

---

.github/workflows/convert-machine-file.yaml

Github action that listens for issues requesting the conversion of machine-files, that then are converted into fluidNc yaml-file and the result is posted to the issue.

convert machine files to yaml triggered by issues
