bdring/Grbl_Esp32

Grbl_Esp32/gcode.cpp
Grbl_Esp32/probe.cpp

added ifdef to allow probe pin to not be defined. Will always indicate not triggered.

Allow for no probe pin

---

Grbl_Esp32/stepper.cpp

stepper_init sets up GPIO directions but not the enable/disable state.
Stops stepper enable pin being driven at 0V (typically enabled) while Wifi initialises.

Disable Steppers at init

---

Grbl_Esp32/report.cpp

Changed FS and F field values from floats to integers.
This change was made to be compatible with LaserGRBL status report parsing (which will not tolerate FS: report with floats), and to be more closely aligned with GRBL real time status report specification documentation, which shows int values in this field rather than floats in the example.

Changed status report number format for FS: and F: fields

---

Grbl_Esp32/system.cpp

This change allows ctrl inputs for door, hold,  resume and reset to be individually disabled, should the not be needed, or are needed for other functions.
Commenting out the pin definition in cpu_map.h will disable the input.

Allow Ctrl inputs to be disabled

---

Grbl_Esp32/grbl.h
Grbl_Esp32/grbl_limits.cpp
Grbl_Esp32/grbl_limits.h

renamed limits.h to grbl_limits.h and updated grbl.h to fix ambiguation issues with limit.h in the esp32 Arduino Framework when compiling with VS-Code/PlatformIO. Fixes INT_MAX not defined compile error as discussed in #74

limit.h disambiguation

---

.gitignore
platformio.ini

Add basic platformio config file with corresponding gitignore file.
Assuming, device is at /dev/ttyUSB4 to compile code and flash it call
> $ pio run --target=upload --upload-port=/dev/ttyUSB4
and to upload SPIFFS command would be
> $ pio run --target=uploadfs --upload-port=/dev/ttyUSB4
Note: I used for testing a ESP32-T board - using baudrate 512000 was working for SPIFFS stable enough, but for code it sometimes failed. If you have same issue, just reduce baudrate in platformio.ini e.g. to 115200.

Add basic platformio config.

---

Grbl_Esp32/gcode.cpp

I would like to report on other matters.
In my environment, raising warning levels will result in compilation errors.
```
(snip)
In file included from /var/folders/tq/mmlh25c96d157qrqgtv3g36w0000gn/T/arduino_build_993650/sketch/grbl.h:36:0,
from /var/folders/tq/mmlh25c96d157qrqgtv3g36w0000gn/T/arduino_build_993650/sketch/config.h:40,
from /var/folders/tq/mmlh25c96d157qrqgtv3g36w0000gn/T/arduino_build_993650/sketch/grbl.h:35,
from /var/folders/tq/mmlh25c96d157qrqgtv3g36w0000gn/T/arduino_build_993650/sketch/gcode.cpp:25:
/var/folders/tq/mmlh25c96d157qrqgtv3g36w0000gn/T/arduino_build_993650/sketch/nuts_bolts.h: In function 'uint8_t gc_execute_line(char*, uint8_t)':
nuts_bolts.h:64:40: error: 'word_bit' may be used uninitialized in this function [-Werror=maybe-uninitialized]
#define …
```

Fix possible reference to uninitialized variables

---

.travis.yml
Grbl_Esp32/gcode.cpp

If that suits your needs, please merge the fixes to enhance Travis CI test items.
- Add a test to enable both BT and WiFi.
- To enable both, change the partition setting to min_spiffs.

Add a Travis CI test to enable both BT and WiFi

---

Grbl_Esp32/report.cpp

- Remove semicolon after F (feed rate)

- Fix error in $G (gcode state) report

---

Grbl_Esp32/cpu_map.h
Grbl_Esp32/grbl.h
Grbl_Esp32/spindle_control.cpp

- Change spindle_stop() off value from 0 to SPINDLE_PWM_OFF_VALUE
- Add example cpu_map.h  CPU_MAP_ESP32_ESC_SPINDLE

Add support for RC ESC based spindles

---

Grbl_Esp32/cpu_map.h
Grbl_Esp32/defaults.h

- Moves a few pins around. Primarily to fix issues with GPIO2 being an input on some dev modules.

Create a V1P2 cpu_map of the MPCNC

---

Grbl_Esp32/grbl.h
Grbl_Esp32/spindle_control.cpp

Simple PR to address the (?debug) messages announcing each PWM power change with:
`[MSG: grbl_analogWrite nnn]`
With LaserWeb these were overwhelming the serial output during rapid laser mode commands. I assume they were put in to assist development of th enew spindle and PWM mapping, but I think they should be commented out for normal use.

Do not send pwm info messages to serial

---

Grbl_Esp32/config.h
Grbl_Esp32/grbl.h
Grbl_Esp32/report.cpp

`USE_SPINDLE_DIR_AS_ENABLE_PIN` is a hangup from ATMega328 days where pins needed to be carefully assigned, GRBL-ESP32 has largely moved to a flexible pin map and this setting no longer does anything practical. But still clutters up config.h in confusing ways..

Strip out USE_SPINDLE_DIR_AS_ENABLE_PIN references

---

Grbl_Esp32/config.h
Grbl_Esp32/grbl.h
Grbl_Esp32/grbl_trinamic.cpp

Typos prevented correct current from being assigned to axes Y through C from saved settings

Fixed typos in grbl_trinamic.cpp

---

Grbl_Esp32/grbl_limits.cpp
Grbl_Esp32/grbl_limits.h
Grbl_Esp32/motion_control.cpp

When squaring axes the first motion with both motors will only do a seek move and a back off, rather than a seek, back off plus a locate, back off squence.
This speeds up the homing sequence. The dual move does not need a locate cycle, because each side will get a locate cycle when they are individually homed.

Auto squaring improvement

---

configure-features.py

Add a small feature to config script that adds a definition to enable if not found in config.h

add the define to enable if it was not found in the block

---

Grbl_Esp32/Grbl_Esp32.ino
Grbl_Esp32/Spindles/BESCSpindle.cpp
Grbl_Esp32/Spindles/DacSpindle.cpp
Grbl_Esp32/Spindles/HuanyangSpindle.cpp
Grbl_Esp32/Spindles/Laser.cpp
Grbl_Esp32/Spindles/NullSpindle.cpp
Grbl_Esp32/Spindles/PWMSpindle.cpp
Grbl_Esp32/Spindles/RelaySpindle.cpp
Grbl_Esp32/Spindles/SpindleClass.cpp
Grbl_Esp32/Spindles/SpindleClass.h
Grbl_Esp32/grbl.h
Grbl_Esp32/stepper.cpp

The core fix was to remove the redundant includes of grbl.h
from the individual spindle.cpp files.  Since those files
are inlined into Grbl_Esp32.ino via nested includes, the
top level include of grbl.h in the .ino covers them.
I also did some cleanups:
- renaming tools/ to Spindles/ .  While "tools" is a good
name in the CNC domain, meaning "toolheads", in the
software domain it typically means "ancillary programs
used for building the software"
- Added a "#pragma once" to grbl.h just in case; it had
no header guard.
- Removed a duplicate #include grbl.h from stepper.cpp
- Deleted some trailing whitespace
- Fixed missing newline at the end of some files

Fix #386 - Arduino compiling problem

---

Grbl_Esp32/Spindles/BESCSpindle.cpp
Grbl_Esp32/Spindles/DacSpindle.cpp
Grbl_Esp32/Spindles/HuanyangSpindle.cpp
Grbl_Esp32/Spindles/Laser.cpp
Grbl_Esp32/Spindles/NullSpindle.cpp
Grbl_Esp32/Spindles/PWMSpindle.cpp
Grbl_Esp32/Spindles/RelaySpindle.cpp

The .cpp files for spindles are included into
one large compilation unit that shares a .h
file, so it should not be necessary to
#include SpindleClass.h in each one, but
Intellisense doesn't know that so it issues
numerous problem reports.  The solution
is to #include SpindleClass.h in each
Spindle*.cpp file, letting the header guard
prevent multiple inclusion during compilation.

Suppress Intellisense problem reports

---

Grbl_Esp32/ProcessSettings.cpp

If you say  $st  and that does not exactly match a setting, it will show all the settings whose names contain the substring "st".  You can also prefix the match string with *, as in $*x , which is useful to force a setting display when there is already an exact match, for example with the $X command.

Partial match of settings names

---

Grbl_Esp32/WebSettings.cpp
Grbl_Esp32/espresponse.h

Some WebUI commands were present even when the
relevant ENABLE_ was not defined,  This corrects
that and make the presence/absense of the various
commands correspond to the old code with different
combinations of web-related enables in config.h
To make things easier to find, the order of the
web command functions in the file now corresponds
with the listed order of the command names.

Fix compile problems with different ENABLE_s

---

Grbl_Esp32/Grbl_Esp32.ino
Grbl_Esp32/Machines/i2s_out_xyzabc_tmc.h
Grbl_Esp32/Motors/MotorClass.cpp
Grbl_Esp32/config.h
Grbl_Esp32/grbl_trinamic.cpp
Grbl_Esp32/grbl_trinamic.h

Fixed a problem in which setting via SPI failed when the I2S I/O expander was used to control the CS pins of the TMC2130.
- Reduce SPI clock to 100KHz
- Moved the start of I2S out execution to just after setup().
Before fix:
```
[MSG:Grbl_ESP32 Ver 1.2a Date 20200605]
[MSG:Compiled with ESP32 SDK:v3.2.3-14-gd3e562907]
[MSG:Using machine:ESP32 SPI 6 Axis Driver Board (Trinamic)]
[MSG:Axis count 6]
[MSG:I2S Steps]
[MSG:TMCStepper Init using Library Ver 0x000602]
[MSG:X Trinamic driver test failed. Check motor power]
[MSG:Y Trinamic driver test failed. Check connection]
[MSG:Z Trinamic driver test failed. Check connection]
[MSG:A Trinamic driver test passed]
[MSG:B Trinamic driver test passed]
[MSG:C Trinamic driver test passed]
[MSG:Init Motors]
[MSG:X Axis standard stepper motor …
```

Fixed the problem of combining I2S and TMC2130 SPI

---

debug.ini
platformio.ini

Requires platformio platform espressif32 version >= 1.12.4

ESP32 Exception decoder

---

Grbl_Esp32/SettingsDefinitions.cpp
Grbl_Esp32/defaults.h
Grbl_Esp32/grbl.h
Grbl_Esp32/grbl_limits.cpp

~~When using TMC's StallGuard sensor-less homing on the I2S ShiftRegister board, a small delay was required at the beginning of Homing.~~
~~Besides that,~~ I'll fix some other things I noticed about the configuration values.

Sensor less homing with I2S OUT

---

configure-features.py

I found a bug in a feature definition script I wrote.
If you explicitly specify enable for a feature that has already been defined, it is doubly enabled.
Before fix:
```bash:
% ./configure-features.py -v -e WIFI -e BLUETOOTH -e SD_CARD
Config path: /Users/odaki/Documents/GitHub/Grbl_Esp32/Grbl_Esp32/config.h
#define ENABLE_BLUETOOTH // enable bluetooth
#define ENABLE_SD_CARD // enable use of SD Card to run jobs
#define ENABLE_WIFI //enable wifi
#if defined(ENABLE_WIFI) || defined(ENABLE_BLUETOOTH)
#define WIFI_OR_BLUETOOTH
#endif
#define ENABLE_HTTP //enable HTTP and all related services
#define ENABLE_OTA  //enable OTA
#define ENABLE_TELNET //enable telnet
#define ENABLE_TELNET_WELCOME_MSG //display welcome string when connect to telnet
#define ENABLE_MDNS //enable mDNS discovery
#define …
```

Fix double-enabled probrem

---

build-all.py
build-machine.py
builder.py

The python build scripts had a dependency on python 2.  Now they work with - and require - python 3.

Fixed python build problem

---

Grbl_Esp32/grbl.h
Grbl_Esp32/protocol.cpp
Grbl_Esp32/serial.cpp
Grbl_Esp32/serial.h

The fix for ^x not clearing the input buffer can be done with an existing function so the addition of a new one was unnecessary.  The existing function had a bug so I fixed that first.

Re fix reset

---

CodingStyle.md
Grbl_Esp32/Grbl_Esp32.ino
Grbl_Esp32/src/Spindles/10vSpindle.cpp
Grbl_Esp32/src/Spindles/10vSpindle.h
Grbl_Esp32/src/Spindles/BESCSpindle.cpp
Grbl_Esp32/src/Spindles/BESCSpindle.h
Grbl_Esp32/src/Spindles/DacSpindle.cpp
Grbl_Esp32/src/Spindles/DacSpindle.h
Grbl_Esp32/src/Spindles/HuanyangSpindle.cpp
Grbl_Esp32/src/Spindles/HuanyangSpindle.h
Grbl_Esp32/src/Spindles/Laser.cpp
Grbl_Esp32/src/Spindles/Laser.h
Grbl_Esp32/src/Spindles/NullSpindle.cpp
Grbl_Esp32/src/Spindles/NullSpindle.h
Grbl_Esp32/src/Spindles/PWMSpindle.cpp
Grbl_Esp32/src/Spindles/PWMSpindle.h
Grbl_Esp32/src/Spindles/RelaySpindle.cpp
Grbl_Esp32/src/Spindles/RelaySpindle.h
Grbl_Esp32/src/Spindles/Spindle.cpp
Grbl_Esp32/src/Spindles/Spindle.h
Grbl_Esp32/src/gcode.cpp

When we have a namespace, we should use it.

Avoid reiterationIteration in spindle names

---

Grbl_Esp32/src/WebUI/Commands.h

The include for Commands.h was incorrect. On Windows this included a `config.h` from the system folder somewhere (note the casing), which it could not find on Linux. On linux, the build failed, as it should.
This fixes the include again. Compiles with build-all on linux.

Fix commands include

---

configure-features.py

Travis CI fails.
This is because the file path in configure-feature.py that I wrote for Travis CI was not able to support the latest source tree.
I've created a small PR, please merge it.

Fix configurator

---

Grbl_Esp32/src/Config.h
Grbl_Esp32/src/GCode.cpp
Grbl_Esp32/src/Grbl.h
Grbl_Esp32/src/I2SOut.cpp
Grbl_Esp32/src/I2SOut.h
Grbl_Esp32/src/Limits.cpp
Grbl_Esp32/src/Machines/6_pack_MPCNC_stepstick_v1.h
Grbl_Esp32/src/Machines/6_pack_stepstick_v1.h
Grbl_Esp32/src/Machines/6_pack_trinamic_V1.h
Grbl_Esp32/src/Machines/esp32_printer_controller.h
Grbl_Esp32/src/Machines/i2s_out_xxyyzz.h
Grbl_Esp32/src/Machines/i2s_out_xyzabc.h
Grbl_Esp32/src/Machines/i2s_out_xyzabc_trinamic.h
Grbl_Esp32/src/MotionControl.cpp
Grbl_Esp32/src/Pins.cpp
Grbl_Esp32/src/ProcessSettings.cpp
Grbl_Esp32/src/Stepper.cpp
Grbl_Esp32/src/Stepper.h

The I2S stepper has two modes.
- I2S static Mode
Short (4-8 μsec) delay, little jitter
- I2S stream mode
Long (10-12 millisec) delay, no jitter
This PR is a proposed change that takes advantage of the strengths of each mode of I2S and uses them to their advantage.
In homing and probing, synchronization of sensor input and motor movement is important. So be sure to use the I2S static mode.
Normal motor movement can generate perfectly precalculated steps in normal motor movement, so use the I2S stream mode for accurate movement. 
However, it is now possible to fix it to I2S static mode in the machine configuration.
`#define DEFAULT_STEPPER ST_I2S_STATIC`
In my environment, it appears to be working as intended.
Please confirm.
```
ets Jun  8 2016 00:22:57
rst:0x1 (POWERON_RESET),boot:0x13 …
```

Dynamically changing the mode of I2S

---

Grbl_Esp32/src/Grbl.h
platformio.ini

When building with PlatfomIO, the local libraries are no longer being used.
As for ArduinoWebsockets, another library of the same name is used, unintentionally.
https://platformio.org/lib/show/6149/ArduinoWebsockets
Originally, the local version 2.1.2 should have been used, but the version 0.4.18, which should not exist, is used.
```
> Executing task: platformio run <
Processing release (platform: espressif32; board: esp32dev; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html …
```

Use local libs with pio

---

Grbl_Esp32/src/CoolantControl.cpp
Grbl_Esp32/src/CoolantControl.h
Grbl_Esp32/src/GCode.cpp
Grbl_Esp32/src/GCode.h
Grbl_Esp32/src/Planner.h
Grbl_Esp32/src/Protocol.cpp
Grbl_Esp32/src/Report.cpp

The approach was
a) Split up the CoolantMode enum, which had become complicated because
it was trying to solve two incompatible requirements, into two
enums GCodeCoolant (a pure enumeration for the use of the GCode
parser) and CoolantState (a bitfield for runtime use where
independent turn-off is possible via overrides)
b) Fixed coolant_set_state() so it can turn off coolant bits
independently.  Previously it could turn them on independently,
but only turn them off simultaneously.  That was fine for M7 M8 M9,
but inadequate for realtime coolant overrides.
c) In the process, I refactored the code in CoolantControl.cpp with
the goal of "saying things once", thus reducing the number of
ifdefs.  When we have the Pin class, the ifdefs will be reduced
even more, perhaps even eliminated. …

Fix #580 Coolant overrides

---

.clang-format
Grbl_Esp32/Custom/atari_1020.cpp

`AllowShortCaseLabelsOnASingleLine: 'true'`
It works for simplifying break-only cases, but to me it feels like over-connecting lines.
This configuration runs the following format.
From:
```C++
default:
grbl_msg_sendf(CLIENT_SERIAL, MsgLevel::Info, "Unknown Switch %d", index);
break;
```
To:
```C++
default: grbl_msg_sendf(CLIENT_SERIAL, MsgLevel::Info, "Unknown Switch %d", index); break;
```
There seems to be a little bit of a change forgotten in the changes you put in to accommodate the enum class State.
We can keep as much of the original code as possible by adding this fix and then adding a small modification to Atari custom.

Suppress one-line case statements and fix atari custom

---

Grbl_Esp32/src/Eeprom.cpp
Grbl_Esp32/src/Eeprom.h
Grbl_Esp32/src/GCode.cpp
Grbl_Esp32/src/GCode.h
Grbl_Esp32/src/ProcessSettings.cpp
Grbl_Esp32/src/Report.cpp
Grbl_Esp32/src/Settings.cpp
Grbl_Esp32/src/Settings.h
Grbl_Esp32/src/SettingsDefinitions.cpp
Grbl_Esp32/src/SettingsStorage.cpp
Grbl_Esp32/src/SettingsStorage.h

1. Revert the change to memcpy_to_eeprom_with_checksum() so
it can be used to read old EEPROM data that was written
with the old broken checksum algorithm
2. Store the coordinate system data in tagged NVS using
a class mechanism modeled on the Settings classes
3. Convert the #defines that defined the coordinate
system indices into an enum, for better error checking.
4. Propagate the old-format EEPROM data into the new format
in a way that is resilient to N_AXIS differences.
5. The new structure avoids unnecessary EEPROM accesses
as a result of the value caching inherent in the Settings-
inspired class structure.  At the same time, it avoids
the possibility of read failure at runtime.
6. Fixed a longstanding FIXME involving the reuse of the
ijk field for non-IJK purposes, thus avoiding …

Store coordinate offsets in NVS

---

Grbl_Esp32/src/Limits.cpp
Grbl_Esp32/src/ProcessSettings.cpp

- Stop creating additional tasks when limit_init() gets called again from homing and resets
- Explicitly delete an object that was causing a memory loss.

Implementing fixes

---

Grbl_Esp32/src/ProcessSettings.cpp
Grbl_Esp32/src/Protocol.cpp
Grbl_Esp32/src/SDCard.cpp
Grbl_Esp32/src/SDCard.h
Grbl_Esp32/src/Settings.cpp
Grbl_Esp32/src/Settings.h
Grbl_Esp32/src/WebUI/ESPResponse.cpp
Grbl_Esp32/src/WebUI/WebSettings.cpp

The main purpose is to handle settings in SD files, so you can have a SD file that establishes a list of setting values.
As a related helpful tool, there is a new command  $Sd/Show=<path>, which displays the contents of <path> on the serial port .  Ideally it would display in the WebUI console window too but I haven't figured that out yet.
One issue with $Sd/Show is that it displays the entire file.  That is okay for short files, e.g. ones containing settings or simple gcode test files, but displaying enormous files can be tedious.  There should be some option for limiting the number of lines shown.

$sd/show and handle settings in SD files

---

Grbl_Esp32/src/WebUI/WebServer.cpp
Grbl_Esp32/src/WebUI/WebServer.h

While eliminating a redundant definition of is_realtime_command(),
I inadvertently introduced a recursion due to the similarity of
the names "is_realtime_command()" and "is_realtime_cmd()".  The
solution is to eliminate the latter entirely.

Fixed WebUI crash

---

Grbl_Esp32/src/Config.h
Grbl_Esp32/src/I2SOut.cpp
Grbl_Esp32/src/I2SOut.h
Grbl_Esp32/src/MachineCommon.h
Grbl_Esp32/src/NutsBolts.h
Grbl_Esp32/src/Stepper.cpp
Grbl_Esp32/src/Stepper.h

More #defines gone
74 lines shorter
Tested by comparing the result of original AMASS computation code to
the new code with values surrounding all of the cutoff frequencies.

Cleaned up AMASS code

---

Grbl_Esp32/src/I2SOut.cpp
Grbl_Esp32/src/Limits.cpp
Grbl_Esp32/src/Motors/Servo.cpp
Grbl_Esp32/src/Motors/TrinamicDriver.cpp
Grbl_Esp32/src/Report.cpp
Grbl_Esp32/src/Report.h
Grbl_Esp32/src/SDCard.cpp
Grbl_Esp32/src/Serial.cpp
Grbl_Esp32/src/Spindles/VFDSpindle.cpp
Grbl_Esp32/src/System.cpp
Grbl_Esp32/src/System.h
Grbl_Esp32/src/WebUI/WebSettings.cpp
platformio.ini

a) closeFile() now does SD.end() to release memory
after running a file from SD.
b) Several task stacks are smaller
c) All tasks now check their free space if DEBUG_REPORT_STACK_FREE
is defined.  platformio.ini has a commented-out line that can be
uncommented to turn that on.
d) Similarly, platformio.ini can turn on DEBUG_REPORT_HEAP_SIZE
e) Fixed a small leak that occurred when listing local files.
With these changes, the heap size tends to hover around 53K, dropping
to about 37K when running a file from SD.

Use less memory

---

Grbl_Esp32/src/CoolantControl.cpp
Grbl_Esp32/src/Grbl.h
Grbl_Esp32/src/Machine.h
Grbl_Esp32/src/Machines/6_pack_Lowrider_stepstick_v1.h
Grbl_Esp32/src/Machines/6_pack_MPCNC_stepstick_v1.h
Grbl_Esp32/src/Machines/6_pack_stepstick_XYZ_v1.h
Grbl_Esp32/src/Machines/6_pack_stepstick_v1.h
Grbl_Esp32/src/Spindles/Laser.cpp

Add coolant pin messages to startup

---

Grbl_Esp32/src/Defaults.h
Grbl_Esp32/src/Error.cpp
Grbl_Esp32/src/Error.h
Grbl_Esp32/src/Exec.cpp
Grbl_Esp32/src/Exec.h
Grbl_Esp32/src/ProcessSettings.cpp
Grbl_Esp32/src/Report.cpp
Grbl_Esp32/src/SettingsDefinitions.cpp
Grbl_Esp32/src/SettingsDefinitions.h
Grbl_Esp32/src/System.h
Grbl_Esp32/src/WebUI/WebSettings.cpp

Similar to $E AKA Errors/List
$E used to be AKA ErrorCodes/List
Also added $Errors/Verbose setting to display
full error text instead of the error number.
It defaults to true because it works with every
sender I have tried so far - cncjs, UGS, LaserGRBL,
and Chrome GCode Sender.  If you have problems with some sender
you can set it to false.

Added $A AKA Alarms/List command

---

Grbl_Esp32/src/Spindles/VFDSpindle.cpp

If a command is critical and fails to receive a response, it should trigger an Alarm. However, because the critical check was only evaluated if the spindle was not already unresponsive, it meant that a critical command failure would be silently ignored if a command failed before it (which could have been a non-critical command). Therefore, I've moved the critical check to occur regardless of whether the spindle was already unresponsive.
Second, I believe that setting `sys_rt_exec_alarm` is not sufficient to stop the machine and put it into alarm state. Other alarm conditions (such as hard limits) also run an `mc_reset()` to stop motion first. It appears that without this, motion will not be stopped, and in fact, the alarm appears to get cleared if it occurs during motion! I've added an …

Fix a few issues with VFDSpindle critical error handling

---

Grbl_Esp32/src/ProcessSettings.cpp
Grbl_Esp32/src/Regex.cpp
Grbl_Esp32/src/Regex.h

Implements only the most basic - and the most
useful - special characters - ^$.*
If the search string does not contain a special
character, it is interpreted as before.  Otherwise
the match is either more strict if anchored by
^ or $, or less strict if it contains a * wildcard .
Some examples:
`$y` - settings that contain y (as before)
`$^y` - settings that start with y
`$y$` - settings that end with y
`$^y*pin` - settings that start with y and contain pin
`$^y*rd$` - settings that start with y and end with rd
Note that `$x` is a classic grbl command as always.  If you want to see settings that contain x, you can write `$*x`.  For settings that start with x, use `$^x` .  In general, this works with any existing Grbl command - by inserting a * , you can force it to be interpreted as a …

Settings filtering via regular expressions

---

Grbl_Esp32/src/Grbl.h
Grbl_Esp32/src/Machines/TMC2209_4x.h
Grbl_Esp32/src/Motors/TrinamicDriver.cpp
Grbl_Esp32/src/Motors/TrinamicUartDriver.h
Grbl_Esp32/src/Motors/TrinamicUartDriverClass.cpp
Grbl_Esp32/src/SettingsDefinitions.cpp

- Added StallGuard homing support to TMC2209 (UART)
- Killed off TMC2208 for now. Too many conflicts with TMC2209. Will return with Diamond motor class hierarchy
- Increase StallGuard setting range for TMC2209. Constrianed in each class to actual limits
- Added a machine def to test TMC2209

TMC2209 Stallguard

---

.gitignore
Grbl_Esp32/src/Spindles/NullSpindle.h
Grbl_Esp32/src/Stepper.cpp

2 small changes. First added laser mode to null spindle for testing. It's not interesting. The other is described below.
We basically have 2 calls to `stepper_pulse_func`, and we do NOT want concurrency there.
One of them is from I2S, which actually calls the function from a critical section (mutex). In other words, there is no issue there.
The other is from `onStepperDriverTimer`, which uses a `busy` flag to check if it's already in use.
Even though `busy` was already volatile, that doesn't mean that the `if` ... `busy = true` is atomic. Other threads might mess things up, so it's better to just get it right. `std::atomic<bool>` with `compare_exchange_strong` does exactly that.

Fixed busy flag in Stepper.cpp by using an atomic compare/exchange op.

---

Grbl_Esp32/src/Grbl.cpp

So machine definitions can change the SPI pins before we talk to
any Trinamic drivers.

Configure motors after I/O pins

---

Grbl_Esp32/src/Grbl.h
Grbl_Esp32/src/Spindles/VFDSpindle.cpp

tl;dr: ISR's don't work well with `grbl_msg_sendf`.
The long story... 
Basically if you do a command like homing that calls motion control, it sets the RPM to value=0 along the homing path. This triggers `set_rpm(0)`, which checks the bounds of the RPM. If 0 is not in bounds, it clamps it to the bounds, sets the RPM and outputs an info message. However, the '0' is not really the issue here, the motion control call is; even with 0, it shouldn't crash.
Well it does. Unfortunately this all happens inside an ISR, which is where this goes wrong. In other words: the last minute change with the info message was a bad idea.
The info message is very helpful though, so we should actually use that when we have the time, -say- when we're calling `set_state` and not `set_rpm`. 
If not, the current …

Fix VFD speed change from ISR

---

Grbl_Esp32/src/Spindles/Spindle.cpp
Grbl_Esp32/src/Spindles/Spindle.h
Grbl_Esp32/src/Spindles/YL620Spindle.cpp
Grbl_Esp32/src/Spindles/YL620Spindle.h

This is a new RS485 VFD driver to support Yalang YL620 type VFDs which are popular in some Chinese CNC spindle kits.
The new class is called SpindleType::YL620
The VFD speaks proper Modbus RTU. Holding register documentation as well as the required parameters to be set on the operator panel of the VFD are included in the associated .cpp file.

Yalang YL620 VFD

---

Grbl_Esp32/src/Grbl.h
platformio.ini

Temporary fix to lost UART rx characters. Reverts esp framework to 1.0.4
https://github.com/espressif/arduino-esp32/issues/5005

Pio down rev
